services:
  api:
    image: avatars-api
    isolation: sandbox
    build:
      context: .
      dockerfile: ./deploy/api.dockerfile
    ports:
      - 5734:80

  web:
    image: avatars-web
    environment:
      API_URL: http://api:5734
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
    ports:
      - 5735:5173
